-- AlterTable
ALTER TABLE "Teklif" ADD COLUMN     "gecerlilikGunu" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN     "kdvDahil" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "kdvOrani" DOUBLE PRECISION NOT NULL DEFAULT 20,
ADD COLUMN     "paraBirimi" TEXT NOT NULL DEFAULT 'TRY';
